var mushroomSaladElements = 
[
    // nodes

    // ingredients (nodes)
    { data: { 
        id: 'dressing-oil',
        type: 'ingredient',
        name: 'Extra-Virgin Olive Oil',
        duration: -1,
        resource: 'pantry',
        amount: 0.5,
        unit: 'cup',
        recipe: 'salad',
        image: 'olive-oil.png',
        context: '',
    } },
    { data: { 
        id: 'cooking-oil',
        type: 'ingredient',
        name: 'Extra-Virgin Olive Oil',
        duration: -1,
        resource: 'pantry',
        amount: 2,
        unit: 'Tbsp',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'wild-mushrooms',
        type: 'ingredient',
        name: 'Mushrooms',
        details: 'Cultivated and/or Wild Mushrooms (cremini, shiitake, oyster, chantrelle, porcini, etc.)',
        duration: 24*4,
        resource: 'fridge',
        amount: 1,
        unit: 'lb',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'unsalted-butter',
        type: 'ingredient',
        name: 'Unsalted Butter',
        duration: 24*7*4,
        resource: 'fridge',
        amount: 1,
        unit: 'Tbsp',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'salt-pepper',
        type: 'ingredient',
        name: 'Salt and Pepper',
        details: 'Kosher Salt and Freshly Ground Black Pepper',
        duration: -1,
        resource: 'pantry',
        amount: -1,
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'shallot',
        type: 'ingredient',
        name: 'Shallot',
        duration: 24*7*4,
        resource: 'pantry',
        amount: 2,
        unit: 'Medium',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'dry-sherry',
        type: 'ingredient',
        name: 'Dry Sherry',
        duration: -1,
        resource: 'pantry',
        amount: 0.25,
        unit: 'cup',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'baby-kale',
        type: 'ingredient',
        name: 'Baby Kale',
        details: 'or use large kale, cut out and discard the rib, and finely shred the leaves',
        duration: 24*4,
        resource: 'fridge',
        amount: 4,
        unit: 'cup',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'sherry-vinegar',
        type: 'ingredient',
        name: 'Sherry Vinegar',
        duration: -1,
        resource: 'pantry',
        amount: 3,
        unit: 'Tbsp',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'dijon-mustard',
        type: 'ingredient',
        name: 'Dijon Mustard',
        duration: 24*7*4*6,
        resource: 'fridge',
        amount: 2,
        unit: 'tsp',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'honey',
        type: 'ingredient',
        name: 'Honey',
        duration: -1,
        resource: 'pantry',
        amount: 2,
        unit: 'tsp',
        recipe: 'salad',
        context: '',
    } },
    { data: { 
        id: 'goat-cheese',
        type: 'ingredient',
        name: 'Fresh Goat Cheese',
        duration: 24*7*2,
        resource: 'fridge',
        amount: 3,
        unit: 'oz',
        recipe: 'salad',
        optional: true,
        context: '',
    } },
    
    // steps (nodes)
    { data: { 
        id: 'wash-mushrooms', 
        type: 'step',
        name: 'Wash',
        text: 'Wash mushrooms.',
        duration: 2,
        active: 2,
        resource: ['sink', 'cutting-board', 'counter'],
        recipe: 'salad',
        order: 10,
        action: 'wash',
        context: '',
    } },
    { data: { 
        id: 'dry-mushrooms', 
        type: 'step',
        name: 'Dry',
        text: 'Wash and dry mushrooms. Trim of woody stems. Thinly slice.',
        duration: 10,
        active: 2,
        resource: ['sink', 'cutting-board', 'counter'],
        recipe: 'salad',
        order: 10,
        action: 'dry',
        context: '',
    } },
    { data: { 
        id: 'wash-kale', 
        type: 'step',
        name: 'Wash',
        text: 'Wash.',
        duration: 2,
        active: 2,
        resource: ['sink', 'salad-spinner', 'counter'],
        recipe: 'salad',
        order: 12,
        action: 'wash',
        context: '',
    } },
    { data: { 
        id: 'dry-kale', 
        type: 'step',
        name: 'Dry',
        text: 'Dry kale.',
        duration: 10,
        active: 2,
        resource: ['sink', 'salad-spinner', 'counter'],
        recipe: 'salad',
        order: 12,
        action: 'dry',
        context: '',
    } },
    { data: { 
        id: 'prep-shallots', 
        type: 'step',
        name: 'Chop',
        text: 'Halve, peel, and rinse shallots. Thinly slice.',
        duration: 5,
        active: 5,
        resource: ['sink', 'cutting-board'],
        recipe: 'salad',
        order: 11,
        action: 'chop',
        context: '',
    } },
    { data: { 
        id: 'cook-mushrooms', 
        type: 'step',
        name: 'Med-High',
        text: 'Heat 2 tablespoons olive oil in a large skillet over high heat until shimmering. Add mushrooms and cook, stirring occasionally, until they\'ve released all their liquid and are browned, about 10 minutes total, reducing heat if oil starts to smoke excessively. Lower heat to medium, and stir in butter and shallots. Cook, stirring often, until butter is melted and shallots soften and turn translucent, about 4 minutes. Season with salt and pepper. Add sherry and cook until mostly evaporated. Remove from heat and keep warm.',
        duration: 10,
        active: 3,
        resource: ['large-skillet', 'burner'],
        recipe: 'salad',
        order: 13,
        action: 'saute',
        context: '',
    } },
    { data: { 
        id: 'cook-shallots', 
        type: 'step',
        name: 'Med',
        text: 'Heat 2 tablespoons olive oil in a large skillet over high heat until shimmering. Add mushrooms and cook, stirring occasionally, until they\'ve released all their liquid and are browned, about 10 minutes total, reducing heat if oil starts to smoke excessively. Lower heat to medium, and stir in butter and shallots. Cook, stirring often, until butter is melted and shallots soften and turn translucent, about 4 minutes. Season with salt and pepper. Add sherry and cook until mostly evaporated. Remove from heat and keep warm.',
        duration: 5,
        active: 2,
        resource: ['large-skillet', 'burner'],
        recipe: 'salad',
        order: 13,
        action: 'saute',
        context: '',
    } },
    { data: { 
        id: 'deglaze', 
        type: 'step',
        name: 'Med',
        text: 'Heat 2 tablespoons olive oil in a large skillet over high heat until shimmering. Add mushrooms and cook, stirring occasionally, until they\'ve released all their liquid and are browned, about 10 minutes total, reducing heat if oil starts to smoke excessively. Lower heat to medium, and stir in butter and shallots. Cook, stirring often, until butter is melted and shallots soften and turn translucent, about 4 minutes. Season with salt and pepper. Add sherry and cook until mostly evaporated. Remove from heat and keep warm.',
        duration: 5,
        active: 2,
        resource: ['large-skillet', 'burner'],
        recipe: 'salad',
        order: 13,
        action: 'saute',
        context: '',
    } },
    { data: { 
        id: 'cool', 
        type: 'step',
        name: 'Cool',
        text: 'Heat 2 tablespoons olive oil in a large skillet over high heat until shimmering. Add mushrooms and cook, stirring occasionally, until they\'ve released all their liquid and are browned, about 10 minutes total, reducing heat if oil starts to smoke excessively. Lower heat to medium, and stir in butter and shallots. Cook, stirring often, until butter is melted and shallots soften and turn translucent, about 4 minutes. Season with salt and pepper. Add sherry and cook until mostly evaporated. Remove from heat and keep warm.',
        duration: 5,
        active: 1,
        resource: ['large-skillet', 'burner'],
        recipe: 'salad',
        order: 13,
        action: 'cool',
        context: '',
    } },
    { data: { 
        id: 'prep-dressing', 
        type: 'step',
        name: 'Dressing',
        text: 'In a small bowl, whisk together the remaining 1/4 cup plus 2 tablespoons olive oil with the sherry vinegar, mustard, and honey. Season with salt and pepper.',
        details: 'Alternatively, add dressing ingredients to a jar, cover, and shake until emulsified. Extra dressing can be kept in the refrigerator for another use.',
        duration: 5,
        active: 5,
        resource: ['small-bowl', 'counter'],
        recipe: 'salad',
        order: 14,
        action: 'bowl',
        context: '',
    } },
    { data: { 
        id: 'dress-salad', 
        type: 'step',
        name: 'Toss',
        text: 'In a large bowl, toss kale with just enough dressing to lightly coat. Add warm mushrooms and toss again. Add more dressing, as needed, to lightly coat all ingredients. Top with goat cheese, if using, and serve.',
        duration: 5,
        active: 5,
        resource: ['large-bowl', 'counter'],
        recipe: 'salad',
        order: 15,
        action: 'bowl',
        context: '',
    } },

    // edges
    { data: {
        id: 'oil-cook',
        source: 'cooking-oil',
        target: 'cook-mushrooms',
        min: 0,
        max: -1,
        amount: 2,
        unit: 'Tbsp',
        recipe: 'salad',
    } },
    { data: {
        id: 'mushrooms-wash',
        source: 'wild-mushrooms',
        target: 'wash-mushrooms',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'mushrooms-dry',
        source: 'wash-mushrooms',
        target: 'dry-mushrooms',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'mushrooms-cook',
        source: 'dry-mushrooms',
        target: 'cook-mushrooms',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'butter-cook',
        source: 'unsalted-butter',
        target: 'cook-shallots',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'salt-pepper-cook',
        source: 'salt-pepper',
        target: 'cook-shallots',
        min: 0,
        max: -1,
        recipe: 'salad',
    } },
    { data: {
        id: 'shallot-prep',
        source: 'shallot',
        target: 'prep-shallots',
        min: 0,
        max: -1,
        recipe: 'salad',
    } },
    { data: {
        id: 'shallot-cook',
        source: 'prep-shallots',
        target: 'cook-shallots',
        min: 0,
        max: 60*24*4,
        recipe: 'salad',
    } },
    { data: {
        id: 'sherry-cook',
        source: 'dry-sherry',
        target: 'deglaze',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'mushrooms-cook',
        source: 'dry-mushrooms',
        target: 'cook-mushrooms',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },

    { data: {
        id: 'oil-dressing',
        source: 'dressing-oil',
        target: 'prep-dressing',
        min: 0,
        max: -1,
        recipe: 'salad',
    } },
    { data: {
        id: 'vinegar-dressing',
        source: 'sherry-vinegar',
        target: 'prep-dressing',
        min: 0,
        max: -1,
        recipe: 'salad',
    } },
    { data: {
        id: 'dijon-dressing',
        source: 'dijon-mustard',
        target: 'prep-dressing',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'honey-dressing',
        source: 'honey',
        target: 'prep-dressing',
        min: 0,
        max: -1,
        recipe: 'salad',
    } },

    { data: {
        id: 'kale-wash',
        source: 'baby-kale',
        target: 'wash-kale',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'kale-dry',
        source: 'wash-kale',
        target: 'dry-kale',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'kale-salad',
        source: 'dry-kale',
        target: 'dress-salad',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },
    { data: {
        id: 'cheese-salad',
        source: 'goat-cheese',
        target: 'dress-salad',
        min: 0,
        max: 60,
        recipe: 'salad',
    } },

    { data: {
        id: 'cook-salad',
        source: 'cool',
        target: 'dress-salad',
        min: 5,
        max: 10,
        weight: 1,
        recipe: 'salad',
    } },
    { data: {
        id: 'dressing-salad',
        source: 'prep-dressing',
        target: 'dress-salad',
        min: 0,
        max: 60*24*7*4,
        recipe: 'salad',
    } },

    { data: {
        id: 'cook-mushrooms-shallots',
        source: 'cook-mushrooms',
        target: 'cook-shallots',
        weight: 1,
        min: 0,
        max: 60*24*7*4,
        recipe: 'salad',
    } },
    { data: {
        id: 'cook-shallots-deglaze',
        source: 'cook-shallots',
        target: 'deglaze',
        weight: 1,
        min: 0,
        max: 60*24*7*4,
        recipe: 'salad',
    } },
    { data: {
        id: 'deglaze-cool',
        source: 'deglaze',
        target: 'cool',
        weight: 1,
        min: 0,
        max: 60*24*7*4,
        recipe: 'salad',
    } },
];

function computeLabel(elements) {
    for(var element of elements) {
        computeElementLabel(element.data);
    }
}

function computeElementLabel(data)
{
    if(data.type == 'step') {
        data.label =  data.name + '\n' + data.duration + ' min, ' + (data.active/data.duration*100).toFixed() + '% active';
    } else if(data.type == 'ingredient') {
        data.label = data.name;
        if(data.amount > 0) {
            data.label = data.amount + ' ' + data.unit + '\n' + data.label;
        }
    } else if(data.type = 'completion') {
        data.label = data.name + ' Ready';
    }
}

computeLabel(mushroomSaladElements);

var styleObj = [ 
    { selector: 'node',
    style: {
        'text-wrap': 'wrap',
        label: 'data(label)',
        width: 100,
        height: 100,
        //'background-image': 'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX31572236.jpg',
        //'background-image-crossorigin': 'use-credentials',
    } }, 
    { selector: 'edge',
    style: {
        'curve-style': 'bezier',
        'target-arrow-color': 'gray',
        'target-arrow-shape': 'triangle'
    } },
    { selector: '[weight > 0]',
    style: {
        'line-color': 'red',
        'target-arrow-color': 'red'
    } },
    { selector: '[type = "ingredient"]',
    style: {
        width: 50,
        height: 50,
    } },
    { selector: '[action = "bowl"]',
    style: {
        'background-color': 'white',
        'background-image': 'bowl.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '[action = "saute"]',
    style: {
        'background-color': 'white',
        'background-image': 'saute.png',
        'background-clip': 'none',
        //'background-fit': 'cover',
        'background-width': '100%',
        'background-height': '50%',
    } },
    { selector: '[action = "wash"]',
    style: {
        'background-color': 'white',
        'background-image': 'wash.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '[action = "dry"], [action = "cool"]',
    style: {
        'background-color': 'white',
        'background-image': 'dry-cool.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '[action = "chop"]',
    style: {
        'background-color': 'white',
        'background-image': 'cutting-board-2.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#dressing-oil, #cooking-oil',
    style: {
        'background-color': 'white',
        'background-image': 'olive-oil.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#unsalted-butter',
    style: {
        'background-color': 'white',
        'background-image': 'butter.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#wild-mushrooms',
    style: {
        'background-color': 'white',
        'background-image': 'mushrooms.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#wild-mushrooms-complete',
    style: {
        'background-image': 'mushrooms.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#shallot',
    style: {
        'background-color': 'white',
        'background-image': 'shallot.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#shallot-complete',
    style: {
        'background-image': 'shallot.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#salt-pepper',
    style: {
        'background-color': 'white',
        'background-image': 'salt-pepper.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#dry-sherry',
    style: {
        'background-color': 'white',
        'background-image': 'liquor.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#honey',
    style: {
        'background-color': 'white',
        'background-image': 'honey.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#dijon-mustard',
    style: {
        'background-color': 'white',
        'background-image': 'mustard.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#baby-kale',
    style: {
        'background-color': 'white',
        'background-image': 'kale.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#baby-kale-complete',
    style: {
        'background-image': 'kale.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#sherry-vinegar',
    style: {
        'background-color': 'white',
        'background-image': 'vinegar.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '#goat-cheese',
    style: {
        'background-color': 'white',
        'background-image': 'goat-cheese.png',
        'background-fit': 'cover',
        'background-clip': 'none',
    } },
    { selector: '[context = "subTree"]',
    style: {
        'background-color': '#c0c0c0',
        width: 50,
        height: 50,
    } },
];

var cy = cytoscape({
    container: document.getElementById('cy'),
    elements: mushroomSaladElements,
    style: styleObj,
});
